### ISSUE TITLE
adding rename in Pv3_export_Polysun.py

### ISSUE THREAD

**Issue by Anass-chakour** [htw-pv3/pvlib-python-pv3#112]
here the name is rewritten

**Comment by Ludee** [comment]
Where is the commit`? You missed the issue number in the message!?

**Comment by Anass-chakour** [comment]
i have no access, i could not get into the reviewers

**Comment by Ludee** [comment]
This is the issue, not the PR.
I don't understand what this issue is about? What is the feature?
