### ISSUE TITLE
Calculate and export weather data for simulation

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/pvlib-python-pv3#13]
We have two different data sets for HTW 2015:

- [ ] htw-wetter (measurements, 1 min)
    - [x] with gaps
    - [ ] filled data
- [x] open_FRED (reanalysis, 15 min)

Calculate and export data that can be used in the simulation software.
There are different parameters that need to be matched and converted.

- [x] HTW: G_hor + G_gen (cmp+si)
- [x] FRED: dhi, dirhi, dni.

Polysun: Gh, Dh und Lh (1s - 1M)
PVsol: Ta Gh FF RH

**Comment by nailend** [comment]
filled weatherdata might not be necessary as hourly average weatherdata is used anyways
