### ISSUE TITLE
Weatherdata in Polysun gives suspicious low output

### ISSUE THREAD

**Issue by khelfen** [htw-pv3/pvlib-python-pv3#17]
Using the generated .csv in Polysun gives a very low feed-in into the grid

~10.6 MWh (Polysun) vs. ~14.7 MWh (PV*Sol) vs. ~16.5 MWh (Measurments)

Assumption: The calculated values for the Read-In in Polysun are off

**Comment by nailend** [comment]
Polysun might you a different conversion model for the diffuse irradiance. 

https://help.valentin-software.com/pvsol/berechnungsgrundlagen/einstrahlung/diffusstrahlung/

Therefore we should find out which one is used by pvsol and use it for the polysun conversion as well.

**Comment by nailend** [comment]
My pvsol simulation settings: (Optionen -> Programmoptionen -> Simulation)

- "Hoffmann" is selected for diffuse Irradiation
- "Hay & Davies" is selected for radiation on inclined plane

Is a model for  "radiation on inclined plane" implemented in polysun as well or neglected?

Additionally, there is the possibility in PVsol to record the diffuse and direct radiation values.
This might of interest for the report.

**Comment by nailend** [comment]
The ["Hofman" Model](https://www.mdpi.com/1996-1073/10/2/248) (developed by valentine software themselves) does not exist in the pvlib as it probably not that popular in the US. 

Therefore I would suggest to change the diffuse model in PVsol to "Erbs" as well to ensure better comparability. 
(Optionen -> Programmoptionen -> Simulation)
