### ISSUE TITLE
Wrong Cords in PVSol .dat data

### ISSUE THREAD

**Issue by khelfen** [htw-pv3/pvlib-python-pv3#25]
The cords in both .dat files needs to be reworked

+ the second entry needs to be negative "13" -> "-13"
+ also not sure if it works with so many decimals

For open_Fred:
+ third entry needs to be replaced with "81"

**Comment by nailend** [comment]
- addded negative sign to longitude header of PVsol in both HTW and open_FRED data
- reduced decimals of lat/lon to 4 digits
- adjusted hight in both header of open_fred data to 81
