### ISSUE TITLE
Calculate parameter for SMA inverter

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/pvlib-python-pv3#32]
pvlib.inverter.fit_sandia(ac_power, dc_power, dc_voltage, dc_voltage_level, p_ac_0, p_nt)

**Comment by Ludee** [comment]
This needs to be solved until tomorrow 30.06.21

**Comment by Mosc5** [comment]
The function fit_sandia seems to require data series to calculate the needed parameters. I wasn't able to infer those from the inverter data sheet.

**Comment by Mosc5** [comment]
The script now finishes without errors and returns the inverter dict. I achieved this by changing the inputs to reflect the inverter efficiency curve. Those values (eta_min, eta_nom, eta_max) are visually approximated and might need adjustment.
