### ISSUE TITLE
Check component database for modules and converters

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/pvlib-python-pv3#4]
- [x] Schott ASI 105 -> created from parameters
- [x] S19L285 -> used from list but changes some parameters
- [x] S18.240 -> created from parameters
- [x] S19.245 -> created from parameters
- [x] Danfoss DLX 2.9 -> created from parameters (from PVSOL parameters)
- [x] SMA SB3000HF -> created from parameters (from efficiency curves)

see:
https://github.com/htw-pv3/pvlib-python-pv3/blob/dev/component_import.py

**Comment by TheBlackBlade** [comment]
I assume this concerns the modules and inverters used for the SonnJA project?

**Comment by TheBlackBlade** [comment]
I have written a short notebook, which filters all databases, that the pvlib queries and saves all entry containing the string "sma"/"danfoss" and "aleo"/"schott" in their name for inverters and modules respectivly and saves them as jsons.
Unfortunately, it is kind of hard to compare and find out, if the parameters are in line with the datasheets for the SonnJA components, since I have not yet found a succinct documentation on what the different parameters represent.
But I have found documentation of the models used: https://sam.nrel.gov/photovoltaic/pv-sub-page-2.html
This is referenced in the documentation of the retrieve_sam method used in pvlib to get the databases.

**Comment by Ludee** [comment]
There is a `SandiaMod` database and a `CEC` database.
Please research where to find them and how to check the parameters!

**Comment by nailend** [comment]
-  ['CECMod']['Aleo_Solar_S19y285']

- ['CECInverter']['Danfoss_Solar__DLX_2_9_UL__208V_', 'Danfoss_Solar__DLX_2_9_UL__240V_']

- ['ADRInverter']['Danfoss_Solar__DLX_2_9_UL__208V__208V__CEC_2013_', 'Danfoss_Solar__DLX_2_9_UL__240V__240V__CEC_2013_']

- ['CECInverter']['SMA_America__SB3000HFUS_30__208V_',
  'SMA_America__SB3000HFUS_30__240V_',
  'SMA_America__SB3000TL_US_22__208V_',
  'SMA_America__SB3000TL_US_22__240V_',
  'SMA_America__SB3000US__208V_',
  'SMA_America__SB3000US__240V_',
  'SMA_America__SB3000US_12__208V_',
  'SMA_America__SB3000US_12__240V_'],
 - ['ADRInverter'] ['Schuco_USA_L_P___Original_Mfg___SMA_America___SB3000US__208V__208V__CEC_NaN_',
  'Schuco_USA_L_P___Original_Mfg___SMA_America___SB3000US__240V__240V__CEC_NaN_',
  'SMA_America__SB3000US_208V__CEC_2007_',
  'SMA_America__SB3000US_240V__CEC_2007_',
  'SMA_Solar_Technology_AG__SB3000HFUS_30__208V_208V__CEC_2011_',
  'SMA_Solar_Technology_AG__SB3000HFUS_30___240V_240V__CEC_2011_',
  'SMA_America__SB3000TL_US_22__208V__208V__CEC_2013_',
  'SMA_America__SB3000TL_US_22__240V__240V__CEC_2013_']}

**Comment by Ludee** [comment]
Inverter data has been checked:
- SMA inverter has been checked, the US version does not fit.
- Danfoss has to be checked as well

It is quite difficult to add new components.
There is a function that must be checked:
https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.inverter.fit_sandia.html

**Comment by Ludee** [comment]
I updated the jupy:

- Rename variables and file names
- Move json output to folder _data_
- Add print functions

There are still all technologies for SonnJA missing.
Please calculate parameters.

**Comment by Ludee** [comment]
Can someone please document the findings.

**Comment by Ludee** [comment]
Parameters for PV and WR are created in this file:
https://github.com/htw-pv3/pvlib-python-pv3/blob/dev/component_import.py
