### ISSUE TITLE
Writing the Readme and a documentation in the Wiki

### ISSUE THREAD

**Issue by BenediktMirwald** [htw-pv3/pvlib-python-pv3#65]
- [x] editing the readme
- [x] editing the wiki documentation
- [x] be happy

**Comment by BenediktMirwald** [comment]
Ich würd im Wiki mal beschreiben, was wir schon alles gemacht haben

**Comment by Stefan254** [comment]
Ich pack eine Übersicht, über die verwendeten Packages ins README

**Comment by FrederikHoener** [comment]
Ich schreib mal eine Einleitung zu Sonnja ins Wiki. 
Vorschlag Gliederung:
- Vorstellung Sonnja, ausführlich
- Ziel der PV Lib
- (Weitere Vorschläge)

**Comment by GitGudCedric** [comment]
Dazu würde ich einfügen:
- eine Übersicht der verwendeten (benötigten) Software

**Comment by GitGudCedric** [comment]
@FrederikHoener Habe für die Vorstellung Sonnja eine Wikiseite erstellt und mache gleich eine für PV Lib/Software. 

Das Ziel gehört meiner Meinung nach zu der Einleitung auf die Homeseite.

**Comment by GitGudCedric** [comment]
Kurzer Zwischenstand zur Wiki:
- What is Sonnja ist erledigt
- Homeseite steht soweit (kann aber gerne noch ausgebaut werden)
- die PV Lib Seite ist noch leer

**Comment by the-dood** [comment]
Habe gerade zur Datenbank der Module und Wechselrichter von pvlib und zu dem Jupyter notebook file was ins readme geschrieben.
https://github.com/htw-pv3/pvlib-python-pv3/issues/72

**Comment by isabel-pixel** [comment]
Habe gerade einen einführenden wiki-Eintrag für PV Lib erstellt. Alle wiki-Seiten können natürlich noch ausgebaut werden, aber ich denke so grob sollte das erstmal passen :)
