### ISSUE TITLE
update CHANGELOG.md

### ISSUE THREAD

**Issue by Siru686** [htw-pv3/pvlib-python-pv3#88]
Updating the CHANGELOG.md

 - [ ]  commit changes

- [x]  pullrequest

- [ ]  merge

**Comment by Ludee** [comment]
The commit does not have the issue number, thus is not connected here. 
You started from an old version, always pull before making changes.

**Comment by Siru686** [comment]
The issue number was added.

**Comment by Ludee** [comment]
You added the issue number to the issue title.
Still can't see the commit. The commit message must contain the number, then it is linked here.
