### ISSUE TITLE
Avoid redundancy in pv3_main.py module

### ISSUE THREAD

**Issue by OussamaKhechine** [htw-pv3/pvlib-python-pv3#94]
Instead of writing several code line for reading the data, we create a read function.

**Comment by Ludee** [comment]
The commit is way too big! 
I cloud find the diff in the corresponding PR:
https://github.com/htw-pv3/pvlib-python-pv3/pull/113/commits/136cbf2b078567e5173128a16fd00e0a66e42696

The improvement of the read function is over engineered. Simple read does the work.
If needed, create a subfunction to check if the file exists and call in read function.
I would not approve the PR.
